-- Seed collection routes with sample data
-- This creates routes for Amuwo Odofin Local Government areas

-- Clear existing routes first
DELETE FROM collection_routes;

INSERT INTO collection_routes (
  "routeCode",
  name,
  ward,
  street,
  zone,
  frequency,
  "serviceDay",
  "startTimeWindow",
  "endTimeWindow",
  "nextCollectionDate",
  status,
  "truckCode",
  notes
) VALUES
  (
    'FES-KIR-001',
    'Festac Town - 1st Avenue Route',
    'Festac Town',
    '1st Avenue',
    'Phase 1',
    'weekly',
    'Monday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '1 day',
    'active',
    'AMW-001',
    'Festac Phase 1 - 1st Avenue residential route'
  ),
  (
    'FES-2ND-002',
    'Festac Town - 2nd Avenue Route',
    'Festac Town',
    '2nd Avenue',
    'Phase 1',
    'weekly',
    'Monday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '1 day',
    'active',
    'AMW-002',
    'Festac Phase 1 - 2nd Avenue afternoon service'
  ),
  (
    'FES-3RD-003',
    'Festac Town - 3rd Avenue Route',
    'Festac Town',
    '3rd Avenue',
    'Phase 1',
    'weekly',
    'Tuesday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '2 days',
    'active',
    'AMW-003',
    'Festac Phase 1 - 3rd Avenue collection'
  ),
  (
    'FES-4TH-004',
    'Festac Town - 4th Avenue Route',
    'Festac Town',
    '4th Avenue',
    'Phase 2',
    'weekly',
    'Tuesday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '2 days',
    'active',
    'AMW-004',
    'Festac Phase 2 - 4th Avenue service'
  ),
  (
    'FES-23R-005',
    'Festac Town - 23 Road Route',
    'Festac Town',
    '23 Road',
    'Phase 2',
    'weekly',
    'Wednesday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '3 days',
    'active',
    'AMW-005',
    'Festac Phase 2 - 23 Road collection'
  ),
  (
    'FES-ABA-006',
    'Festac Town - Abakpa Street Route',
    'Festac Town',
    'Abakpa Street',
    'Phase 3',
    'weekly',
    'Wednesday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '3 days',
    'active',
    'AMW-006',
    'Festac Phase 3 - Abakpa Street service'
  ),
  (
    'AMU-AGE-007',
    'Amuwo - Agege Motor Road Route',
    'Amuwo',
    'Agege Motor Road',
    'Mile 2',
    'weekly',
    'Thursday',
    '06:00',
    '10:00',
    NOW() + INTERVAL '4 days',
    'active',
    'AMW-007',
    'Early morning collection for Agege Motor Road commercial area'
  ),
  (
    'AMU-OKO-008',
    'Amuwo - Okota Road Route',
    'Amuwo',
    'Okota Road',
    'Okota',
    'weekly',
    'Thursday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '4 days',
    'active',
    'AMW-008',
    'Okota Road residential and commercial route'
  ),
  (
    'AMU-ISO-009',
    'Amuwo - Isolo Road Route',
    'Amuwo',
    'Isolo Road',
    'Isolo',
    'weekly',
    'Friday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '5 days',
    'active',
    'AMW-009',
    'Isolo Road collection service'
  ),
  (
    'KIR-OLA-010',
    'Kirikiri - Olabisi Street Route',
    'Kirikiri',
    'Olabisi Street',
    'Kirikiri Town',
    'weekly',
    'Friday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '5 days',
    'active',
    'AMW-010',
    'Kirikiri Town - Olabisi Street route'
  ),
  (
    'KIR-APO-011',
    'Kirikiri - Apongbon Street Route',
    'Kirikiri',
    'Apongbon Street',
    'Kirikiri Town',
    'biweekly',
    'Monday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '1 day',
    'active',
    'AMW-011',
    'Kirikiri Town - Apongbon Street biweekly service'
  ),
  (
    'MAZ-OLA-012',
    'Mazamaza - Oluti Street Route',
    'Mazamaza',
    'Oluti Street',
    'Mazamaza',
    'weekly',
    'Monday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '1 day',
    'active',
    'AMW-012',
    'Mazamaza - Oluti Street afternoon collection'
  ),
  (
    'MAZ-VOL-013',
    'Mazamaza - Volkswagen Bus Stop Route',
    'Mazamaza',
    'Volkswagen Bus Stop Area',
    'Mazamaza',
    'weekly',
    'Tuesday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '2 days',
    'active',
    'AMW-013',
    'Volkswagen area collection route'
  ),
  (
    'TRA-BAD-014',
    'Trade Fair - Badagry Expressway Route',
    'Trade Fair',
    'Badagry Expressway',
    'Trade Fair Complex',
    'weekly',
    'Wednesday',
    '06:00',
    '10:00',
    NOW() + INTERVAL '3 days',
    'active',
    'AMW-014',
    'Early morning Trade Fair Complex route'
  ),
  (
    'TRA-OJO-015',
    'Trade Fair - Ojo Road Route',
    'Trade Fair',
    'Ojo Road',
    'Satellite Town',
    'weekly',
    'Wednesday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '3 days',
    'active',
    'AMW-015',
    'Satellite Town - Ojo Road service'
  ),
  (
    'SAT-ALA-016',
    'Satellite Town - Alakija Road Route',
    'Satellite Town',
    'Alakija Road',
    'Alakija',
    'weekly',
    'Thursday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '4 days',
    'active',
    'AMW-016',
    'Alakija residential area collection'
  ),
  (
    'SAT-AGU-017',
    'Satellite Town - Aguda Street Route',
    'Satellite Town',
    'Aguda Street',
    'Satellite',
    'weekly',
    'Thursday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '4 days',
    'active',
    'AMW-017',
    'Satellite Town - Aguda Street route'
  ),
  (
    'MIL-OKO-018',
    'Mile 2 - Okota Road Junction Route',
    'Mile 2',
    'Okota Road Junction',
    'Mile 2',
    'weekly',
    'Friday',
    '06:00',
    '10:00',
    NOW() + INTERVAL '5 days',
    'active',
    'AMW-018',
    'Mile 2 commercial junction early service'
  ),
  (
    'VOL-IKE-019',
    'Volkswagen - Ikeja Road Route',
    'Volkswagen',
    'Ikeja Road',
    'Volkswagen',
    'biweekly',
    'Friday',
    '13:00',
    '17:00',
    NOW() + INTERVAL '5 days',
    'active',
    'AMW-019',
    'Volkswagen - Ikeja Road biweekly collection'
  ),
  (
    'FES-FIN-020',
    'Festac Town - Finecoat Road Route',
    'Festac Town',
    'Finecoat Road',
    'Phase 3',
    'weekly',
    'Monday',
    '07:00',
    '11:00',
    NOW() + INTERVAL '1 day',
    'active',
    'AMW-020',
    'Festac Phase 3 - Finecoat Road service'
  )
ON CONFLICT ("routeCode") DO NOTHING;

-- Display inserted routes
SELECT 
  "routeCode",
  name,
  ward,
  street,
  "serviceDay",
  "nextCollectionDate",
  status
FROM collection_routes
ORDER BY ward, street;
